### ISSUE TITLE
Stock problems

### ISSUE THREAD

**Issue by pkozakiewicz** [sinara-hw/AUX_PSU#10]
I would like to address some availability problems:

LT3090HMSE#PBF - can we use different temperature range version? (EMSE, IMSE),
LT8362IDD#TRPBF - same as above (EDD),
LM75AIMM/NOPB - is there any 1:1 replacement?

**Comment by gkasprow** [comment]
Yes, you can use another temp range.
LM75BIM-5/NOPB would work

**Comment by pkozakiewicz** [comment]
These are another two shortages:

1SMB5916BT3G
3059Y-1-254LF

**Comment by martafafara** [comment]
Most of above parts had only temporary stock problems, except LM75AIMM/NOPB which is obsolete. TI recommended replacement: LM75AIMMX/NOPB.
Detailed analysis of BOM revealed additional necessary changes:
CD4028BM-> CD4028BM96
GRM219R61E106KA12D ->TMK212BBJ106KGHT
