### ISSUE TITLE
LT3089IFE - too high dropout voltage - extra power dissipation

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/AUX_PSU#15]
Dropout voltage at both LDOs is unnecessarily set too high (more than 3.9 V) causing extra power dissipation (even 1.5 - 2 W extra power on each LDO).

According to the LDO spec 2 V would be more than enough.
Set R13/R24 and R18/R14.

![obraz](https://user-images.githubusercontent.com/25741678/145414490-25524425-ffe9-4d00-b33b-9ddb6d6afe06.png)

**Comment by gkasprow** [comment]
I added 120k in parallel to R24, R14 and now the dropout is 1.7V

**Comment by gkasprow** [comment]
negative LDO is already 2V

**Comment by gkasprow** [comment]
we need to leave them 120k
