### ISSUE TITLE
Negative voltage channel - wrong feedback circuit

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/AUX_PSU#16]
Feedback circuit (driving DC/DC voltage level) is wrong designed - no way to work properly.

![obraz](https://user-images.githubusercontent.com/25741678/145439535-86917328-10a1-49dc-a146-7dba14c5fd65.png)

**Comment by gkasprow** [comment]
@michalgaska

**Comment by gkasprow** [comment]
it should be a pnp + base divider

**Comment by mkiepiela** [comment]
Fixed.
