### ISSUE TITLE
[Schematic review] T28 always open

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/AUX_PSU#8]
What is the purpose of T28?
It will be always open, regardless if Kasli is connected or not (P3V3_MP exists or not).

![obraz](https://user-images.githubusercontent.com/25741678/124121150-d20c1200-da74-11eb-8490-e15113e39878.png)

**Comment by gkasprow** [comment]
It's a voltage translator

**Comment by mkiepiela** [comment]
Take a look at this once again, please. It does not look like voltage translator.
P-MOS will be always open. On the En line will be more than 8V (R57/R98 voltage divider additionally pulled up by R64 and LD1D).

**Comment by gkasprow** [comment]
Right! There should be NMOS. I didn't notice that PMOS was used instead
