### ISSUE TITLE
[Schematic review] Temperature sensor - to high voltage at O.S. output

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/AUX_PSU#9]
Voltage at O.S. pin of LM75 (IC14) must be less than 6.5V.
It is exceeded. Except R57/R98 voltage divider, this net is also pulled up by R64, LD1D (and open T28).

**Comment by gkasprow** [comment]
that's the role of T28 to make sure the rail won't exceed 3V3

**Comment by mkiepiela** [comment]
Doesn't seem to work. Details:
https://github.com/sinara-hw/AUX_PSU/issues/8

**Comment by gkasprow** [comment]
that should work 
![obraz](https://user-images.githubusercontent.com/4325054/129892569-9fa83fff-15b7-43c8-8b42-feb0001c1ee5.png)
